import { test, expect } from '@playwright/test'

test('Expressチュートリアルの実APIで追加・編集・再読込・削除・エラー復旧を体験する', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Expressチュートリアル', exact: true }).click()
  await page.getByRole('button', { name: 'メニューを閉じる', exact: true }).click()
  const demo = page.getByRole('region', { name: 'API実演', exact: true })
  const title = `API実演-${Date.now()}`
  await demo.getByLabel('実演のタスク名').fill(title)
  await demo.getByRole('button', { name: '追加', exact: true }).click()
  await expect(demo.getByRole('checkbox', { name: title, exact: true })).toBeVisible()
  await demo.getByRole('textbox', { name: `${title}の編集` }).fill(`${title}-編集`)
  await demo.getByRole('listitem').filter({ hasText: title }).getByRole('button', { name: '保存' }).click()
  await demo.getByRole('checkbox', { name: `${title}-編集`, exact: true }).click()
  await expect(demo.getByRole('status')).toHaveText('完了状態を保存しました。')
  await page.reload()
  await expect(demo.getByRole('checkbox', { name: `${title}-編集`, exact: true })).toBeChecked()
  await demo.screenshot({ path: '/tmp/api-tutorial-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await demo.screenshot({ path: '/tmp/api-tutorial-mobile.png' })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const editForm = demo.locator('.api-demo-edit').filter({ has: page.getByRole('textbox', { name: `${title}-編集の編集` }) })
  const field = await editForm.getByRole('textbox').boundingBox()
  const save = await editForm.getByRole('button', { name: '保存' }).boundingBox()
  expect(field!.width).toBeGreaterThan(100)
  expect(save!.x).toBeGreaterThanOrEqual(field!.x + field!.width)
  await demo.getByRole('listitem').filter({ hasText: title }).getByRole('button', { name: '削除' }).click()
  await expect(demo.getByRole('checkbox', { name: `${title}-編集`, exact: true })).toHaveCount(0)
  await demo.getByRole('button', { name: '404エラーを試す' }).click()
  await expect(demo.getByRole('alert')).toContainText('HTTP 404')
  await demo.getByRole('button', { name: '再取得', exact: true }).click()
  await expect(demo.getByRole('alert')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('スクロール後のプレビュー上端にヘッダー分の余白が残らない', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('hook-lab-selected-chapter', 'basic-06')
    localStorage.setItem('hook-lab-sidebar-collapsed', 'true')
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Expressで取得と保存', exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 200))
  await expect.poll(() => page.locator('#task-preview').evaluate(element => Math.round(element.getBoundingClientRect().top))).toBe(0)
})
